export { default as Home } from './home'
export { default as Calculator } from './calculator'
export { default as Service } from './service'
export { default as Contact } from './contact'
export { default as Form } from './form'
export { default as Calendar } from './calendar'
export { default as ApolloClient } from './apolloClient'
